const names=["PAGER","COAL IRON","WINNOWING FAN","PANCH PHORON BOX","GRAIN MEASURING BOX","ICE BOX","BUTTER CHURN","YARN SWIFT","FOOT WARMER","WATER WELL","SCHOOL DESK","ROCKING HORSE","HAND WATER PUMP","THERMOS FLASK","TABLE FAN","POST BOX","PENCIL SHARPENER","SEWING MACHINE","OLD SCALE","WOODEN TRUNK","MILK CAN","HAND BELL","CANE BASKET","TIN LUNCHBOX","WOODEN RULER","INKWELL","ABACUS","WOODEN TOY","CLOTHES WRINGER","CANDLE SNUFFER","WICK TRIMMER","COBBLER LAST","WOODEN MOULD","IRON MORTAR","BRASS LADLE","PALM LEAF FAN"];let shown=12;const key="last404_state";let s=JSON.parse(localStorage.getItem(key)||'{"registered":false,"id":"","score":0,"referrals":0}');
const cfg=window.LAST404_CONFIG||{DEMO_MODE:true};
const sb=(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!cfg.DEMO_MODE)?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;const qs=new URLSearchParams(location.search);document.getElementById("ref").textContent=qs.get("ref")||"NONE";
function save(){localStorage.setItem(key,JSON.stringify(s));dash()}function dash(){status.textContent=s.registered?"ARCHIVE CONFIRMED":"NOT REGISTERED";did.textContent=s.id||"—";score.textContent=s.score;refs.textContent=s.referrals;link.textContent=s.registered?location.origin+location.pathname+"?ref="+s.id:"Register first to generate your link."}function render(){grid.innerHTML="";names.slice(0,shown).forEach((n,i)=>grid.insertAdjacentHTML("beforeend",`<article class="card"><span class="num">ARCHIVE / ${String(i+1).padStart(3,"0")}</span><div class="object">${String(i+1).padStart(3,"0")}</div><div><h3>${n}</h3><small>STATUS: FORGOTTEN</small></div></article>`))}render();dash();
more.onclick=()=>{if(shown<names.length){shown=Math.min(shown+12,names.length);render()}else toast("THE ARCHIVE IS FULL")};
form.onsubmit=async e=>{e.preventDefault();const walletValue=wallet.value.trim();const xValue=x.value.trim();if(!walletValue||!xValue)return toast("Complete the required fields");
if(sb){
  const archiveId="A-"+Math.floor(100000+Math.random()*900000);
  const referralCode=archiveId;
  const referredBy=new URLSearchParams(location.search).get("ref");
  const {error}=await sb.from("archivists").insert({archive_id:archiveId,wallet_address:walletValue,x_username:xValue,community_username:community.value.trim()||null,referral_code:referralCode,referred_by:referredBy||null,score:10});
  if(error){if(error.code==="23505") return toast("This wallet is already registered"); return toast("Registration failed — check backend setup");}
  s={...s,registered:true,id:archiveId,score:10};save();form.hidden=true;success.hidden=false;aid.textContent=archiveId;toast("Archive entry confirmed");
}else{
  s.registered=true;s.id=s.id||"A-"+Math.floor(1000+Math.random()*9000);s.score=Math.max(s.score,10);save();form.hidden=true;success.hidden=false;aid.textContent=s.id;toast("Demo entry confirmed");
}};
document.querySelectorAll("[data-m]").forEach(x=>x.onclick=()=>{const m=x.dataset.m;if(m==="ref"){if(!s.registered)return toast("Register first");navigator.clipboard?.writeText(link.textContent);toast("Referral link copied");return}s.score=Math.min(100,s.score+15);save();x.querySelector("button").textContent="DONE";toast("Mission recorded")});
copy.onclick=()=>{if(!s.registered)return toast("Register first");navigator.clipboard?.writeText(link.textContent);toast("Referral link copied")};menu.onclick=()=>{document.querySelector("nav").style.display="flex";document.querySelector("nav").style.position="absolute";document.querySelector("nav").style.top="76px";document.querySelector("nav").style.left="0";document.querySelector("nav").style.right="0";document.querySelector("nav").style.padding="20px";document.querySelector("nav").style.background="#050505";document.querySelector("nav").style.flexDirection="column"};function toast(x){const t=document.getElementById("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}